WEBBook/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WEBBook.Models;
using WEBBook.Repository.IRepository;

namespace WEBBook.Controllers
{
    public class AutorController : Controller
    {
        private readonly IAutorRepository autorRepository;
        private readonly IConfiguration configuration;

        public AutorController(IAutorRepository autorRepository, IConfiguration configuration)
        {
            this.autorRepository = autorRepository;
            this.configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            return View(await autorRepository.GetAllAsync(configuration["APIAuthor:BaseUrl"]));
        }
        public IActionResult Create()
        {
            return View(new Autor());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Autor autor)
        {
            if (ModelState.IsValid)
            {
                var modelError = await autorRepository.CreateAsync(configuration["APIAuthor:BaseUrl"], autor);
                if (modelError.Response.Errors.Count > 0)
                {
                    autor.Errors = new List<Errors>();
                    foreach (var item in modelError.Response.Errors)
                    {
                        autor.Errors.Add(item);
                    }
                    return View(autor);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(autor);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            Autor autor = new Autor();
            if (id == null) return NotFound();
            autor = await autorRepository.GetAsync(configuration["APIAuthor:BaseUrl"], id.GetValueOrDefault());
            if (autor == null) return NotFound();
            return View(autor);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Autor autor)
        {
            if (ModelState.IsValid)
            {
                var modelError = await autorRepository.UpdateAsync(configuration["APIAuthor:BaseUrl"] + autor.IdAutor, autor);
                if (modelError.Response.Errors.Count > 0)
                {
                    autor.Errors = new List<Errors>();
                    foreach (var item in modelError.Response.Errors)
                    {
                        autor.Errors.Add(item);
                    }
                    return View(autor);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(autor);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            Autor autor = new Autor();
            if (id == null) return NotFound();
            autor = await autorRepository.GetAsync(configuration["APIAuthor:BaseUrl"], id.GetValueOrDefault());

            if (autor == null) return NotFound();
            return View(autor);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var autor = await autorRepository.GetAsync(configuration["APIAuthor:BaseUrl"], id);
            if (autor == null) return NotFound();

            var modelError = await autorRepository.DeleteAsync(configuration["APIAuthor:BaseUrl"], autor.IdAutor);
            if (modelError.Response.Errors.Count > 0)
            {
                autor.Errors = new List<Errors>();
                foreach (var item in modelError.Response.Errors)
                {
                    autor.Errors.Add(item);
                }
                return View(autor);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<JsonResult> GetAuthors()
        {
             var autor = await autorRepository.GetAllAsync(configuration["APIAuthor:BaseUrl"]);
            return Json(new { Data = autor });
        }
    }
}

WEBBook/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WEBBook.Models;
using WEBBook.Repository.IRepository;
using WEBBook.Resource;

namespace WEBBook.Controllers
{
    public class EstudianteController : Controller
    {
        private readonly IEstudianteRepository estudianteRepository;
        private readonly IConfiguration configuration;

        public EstudianteController(IEstudianteRepository estudianteRepository, IConfiguration configuration)
        {
            this.estudianteRepository = estudianteRepository;
            this.configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<JsonResult> GetStudents()
        {
            var estudiantes = await estudianteRepository.GetAllAsync(configuration["APIStudent:BaseUrl"]);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> GetStudent(int id)
        {
            var estudiantes = await estudianteRepository.GetAsync(configuration["APIStudent:BaseUrl"], id);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> UpdateStudent(Estudiante estudiante)
        {
            var estudiantes = await estudianteRepository.UpdateAsync(configuration["APIStudent:BaseUrl"] + estudiante.IdLector, estudiante);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> CreateStudent(Estudiante estudiante)
        {
            var estudiantes = await estudianteRepository.CreateAsync(configuration["APIStudent:BaseUrl"], estudiante);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> DeleteStudent(int id)

        {
            var estudiantes = await estudianteRepository.DeleteAsync(configuration["APIStudent:BaseUrl"], id);
            return Json(new { Data = estudiantes });
        }
    }
}

WEBBook/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WEBBook.Models;
using WEBBook.Repository.IRepository;

namespace WEBBook.Controllers
{
    public class LibroController : Controller
    {
        private readonly ILibroRepository libroRepository;
        private readonly ILibAutRepository libAutRepository;
        private readonly IConfiguration configuration;

        public LibroController(ILibroRepository libroRepository, ILibAutRepository libAutRepository, IConfiguration configuration)
        {
            this.libroRepository = libroRepository;
            this.libAutRepository = libAutRepository;
            this.configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<JsonResult> GetBooks()
        {
            var libros = await libroRepository.GetAllAsync(configuration["APIBook:BaseUrl"]);
            return Json(new { Data = libros });
        }
        public async Task<JsonResult> GetBook(int id)
        {
            var estudiantes = await libroRepository.GetAsync(configuration["APIBook:BaseUrl"], id);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> UpdateBook(Libro libro)
        {
            var estudiantes = await libroRepository.UpdateAsync(configuration["APIBook:BaseUrl"] + libro.IdLibro, libro);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> CreateBook(Libro libro)
        {
            var estudiantes = await libroRepository.CreateAsync(configuration["APIBook:BaseUrl"], libro);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> DeleteBook(int id)
        {
            var estudiantes = await libroRepository.DeleteAsync(configuration["APIBook:BaseUrl"], id);
            return Json(new { Data = estudiantes });
        }

        public async Task<JsonResult> AssignAuthor(LibAut libAut)
        {
            await libAutRepository.CreateAsync(configuration["APIBook:BaseUrl"] + "AssignAuthor", libAut);
            return Json(new { Data = string.Empty });
        }
    }
}

WEBBook/Controllers/PrestamoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WEBBook.Models;
using WEBBook.Repository.IRepository;
using WEBBook.Resource;

namespace WEBBook.Controllers
{
    public class PrestamoController : Controller
    {
        private readonly IPrestamoRepository prestamoRepository;
        private readonly IStudentBookRepository studentBookRepository;
        private readonly IConfiguration configuration;

        public PrestamoController(IPrestamoRepository prestamoRepository, IStudentBookRepository studentBookRepository, IConfiguration configuration)
        {
            this.prestamoRepository = prestamoRepository;
            this.studentBookRepository = studentBookRepository;
            this.configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<JsonResult> LendBooks(StudentBook studentBook)
        {
            var estudiantes = await studentBookRepository.CreateAsync(configuration["APIBorrowed:BaseUrl"] + Util.LendBooks, studentBook);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> GetBooksBorrowed()
        {
            var estudiantes = await prestamoRepository.GetAllAsync(configuration["APIBorrowed:BaseUrl"]);
            return Json(new { Data = estudiantes });
        }
        public async Task<JsonResult> ReturnBooks(StudentBook studentBook)
        {
            var estudiantes = await studentBookRepository.CreateAsync(configuration["APIBorrowed:BaseUrl"] + Util.ReturnBooks, studentBook);
            return Json(new { Data = estudiantes });
        }
    }
}

WEBBook/Views/Shared/_ButtonOptionsPartial.cshtml
@model string
<div class="row">
    <div class="col-6">
        <input type="submit" class="@(Model == "Delete"?"btn btn-danger form-control":"btn btn-info form-control")" value="@Model" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
    </div>
</div>

WEBBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEBBook</title>
    <script src="~/jquery/jquery.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/sweetalert/sweetalert.css" rel="stylesheet" />
    <script src="~/sweetalert/sweetalert.js"></script>
    <script src="~/moment.js/moment.js"></script>
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WEBBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Mantenimiento
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Autor" asp-action="Index">Autor</a>
                                <a class="dropdown-item" asp-controller="Libro" asp-action="Index">Libro</a>
                                <a class="dropdown-item" asp-controller="Estudiante" asp-action="Index">Estudiante</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prestamo" asp-action="Index">Préstamo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WEBBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WEBBook/Views/Shared/_TableButtonPartial.cshtml
@model int
<div class="btn-group" role="group">
    <a class="btn btn-sm btn-info text-white" title="Editar" asp-action="Edit" asp-route-Id="@Model"><i class="fa fa-pencil"></i></a>
    <a class="btn btn-sm btn-danger text-white" title="Eliminar" asp-action="Delete" asp-route-Id="@Model"><i class="fa fa-trash" aria-hidden="true"></i></a>
</div>